<style>
/* Make "Add a media object" smaller */
.col-sm-3 .text-center {
    font-size: 80%;
}
</style>

<?php

$view = view('::individual-page', get_defined_vars());

$view = preg_replace('/<div class="img-thumbnail">(\r\n|\r|\n|\s)+<i class="wt-individual-silhouette/', '<div class="img-thumbnail text-center"><i class="wt-individual-silhouette', $view); // Center silhouette for individuals without images
$view = preg_replace('/nav-tabs/', 'nav-pills', $view); // Change second tabs to pills

echo $view;
