<?php

$view = view('::place-hierarchy', get_defined_vars());

// Make list header a heading
$view = preg_replace('/<span class="col wt-page-options-label me-1">/', '<h6 class="col wt-page-options-label me-1 text-center">', $view);
$view = preg_replace('/<\/span>(\r\n|\r|\n)<\/div>/', '</h6></div>', $view);

$view = preg_replace('/list-unstyled/', '', $view); // Make list normal
$view = preg_replace('/list_table/', 'list_table mx-auto', $view); // Center list

echo $view;
