<?php

use Fisharebest\Webtrees\I18N;

?>

<div class="row">
            <h5 class="col list_label text-center">
                <?= I18N::translate('Place list') ?>
            </h5>
</div>
<div class="row">
    <?php foreach ($columns as $column) : ?>
        <ul class="col list_value_wrap mr-1">
            <?php foreach ($column as $item) : ?>
                <li>
                    <a href="<?= e($item->url()) ?>"><?= $item->fullName() ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endforeach ?>
</div>
