<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Tree;

/**
 * @var bool            $is_admin
 * @var Individual      $individual
 * @var array<stdClass> $stories
 * @var Tree            $tree
 */

?>

<div class="wt-tab-stories py-4">
    <?php foreach ($stories as $story) : ?>
        <?
        /**
         * Add a container for each story
         */
        ?>
        <article class="story mb-4 pb-4">
            <header class="story_title descriptionbox text-center rela">
                <h4><?= e($story->title) ?></h4>
            </header>
            <div class="story_body optionbox">
                <?= $story->story_body ?>
            </div>
            <?php if ($is_admin) : ?>
                <footer class="story_edit text-right">
                    <a href="<?= e(route('module', ['module' => 'stories', 'action' => 'AdminEdit', 'block_id' => $story->block_id, 'tree' => $tree->name(), 'url' => $individual->url()])) ?>" class="btn btn-link">
                        <?= view('icons/edit') ?>
                        <?= I18N::translate('Edit the story') ?>
                    </a>
                </footer>
            <?php endif ?>
        </article>
    <?php endforeach ?>

    <?
    /**
     * Display Add link even when there are existing stories
     */
    ?>
    <?php if ($is_admin) : ?>
        <div>
            <a href="<?= e(route('module', ['module' => 'stories', 'action' => 'AdminEdit', 'xref' => $individual->xref(), 'tree' => $tree->name(), 'url' => $individual->url()])) ?>">
                <?= I18N::translate('Add a story') ?>
            </a>
        </div>
    <?php endif ?>
</div>