<?php

use Fisharebest\Webtrees\I18N;

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<ul class="faq_list">
    <?php foreach ($faqs as $id => $faq) : ?>
    <li>
            <a href="#faq<?= e($id) ?>"><?= e($faq->header) ?></a>
    </li>
    <?php endforeach ?>
</ul>

<?php foreach ($faqs as $id => $faq) : ?>
    <article class="faq">
        <header class="faq_title" id="faq<?= $id ?>">
            <h3><?= e($faq->header) ?></h3>
            <span class="faq_top">
                <a href="#content"><?= I18N::translate('back to top') ?></a>
            </span>
        </header>
        <main class="faq_body">
            <?= substr($faq->faqbody, 0, 1) === '<' ? $faq->faqbody : nl2br(e($faq->faqbody), false) ?>
        </main>
    </article>
<?php endforeach ?>
