<?php

/**
 * Convert TOC from table to list, style questions, and adjust back-to-top anchor
 */

use Fisharebest\Webtrees\I18N;
use Illuminate\Support\Collection;

/**
 * @var Collection<int,object> $faqs
 * @var string                 $title
 */

?>

<h2 class="wt-page-title"><?= $title ?></h2>

<ul class="faq_list">
    <?php foreach ($faqs as $id => $faq) : ?>
    <li>
            <a href="#faq<?= e($id) ?>"><?= e($faq->header) ?></a>
    </li>
    <?php endforeach ?>
</ul>

<?php foreach ($faqs as $id => $faq) : ?>
    <article class="faq">
        <header class="faq_title" id="faq<?= $id ?>">
            <h3><?= e($faq->header) ?></h3>
            <span class="faq_top">
                <a href="#content"><?= I18N::translate('back to top') ?></a>
            </span>
        </header>
        <main class="faq_body">
            <?= str_starts_with($faq->faqbody, '<') ? $faq->faqbody : nl2br(e($faq->faqbody), false) ?>
        </main>
    </article>
<?php endforeach ?>
