<style>
    /* Increase padding around entries in relatives list */
    /* Need to override this Bootstrap class in this case because entries are loaded dynamically */
    .gchart.px-md-2 {
        padding: 1.5rem !important;
    }
</style>

<?php

$view = view('::modules/pedigree-map/chart', get_defined_vars());
$view = preg_replace('/list-unstyled px-1/', 'list-unstyled', $view); // Remove spacing outside horizontal separators in relatives list

echo $view;
