<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Illuminate\Support\Collection;

/**
 * @var int                  $limit_low
 * @var int                  $limit_high
 * @var Collection<stdClass> $rows
 * @var bool                 $show_user
 */

?>

<div class="list-group">
<?php foreach ($rows as $n => $row) : ?>
    <?php if ($n === $limit_low && $rows->count() > $limit_high) : ?>
        <div>
            <button class="btn btn-sm btn-secondary my-3" id="show-more-<?= e($id) ?>">
                <?= view('icons/add') ?>
                <?= /* I18N: button label */ I18N::translate('show more') ?>
            </button>
        </div>
    <?php endif ?>

    <a href="<?= e($row->record->url()) ?>" class="<?= $n >= $limit_low && $rows->count() > $limit_high ? 'd-none' : '' ?> list-group-item list-group-item-action">
        <span class="d-block"><?= $row->record->fullName() ?></span>

        <?php if ($row->record->lastChangeTimestamp()->unix() !== 0) : ?>
            <small class="d-block">
                <?php if ($show_user) : ?>
                    <?= /* I18N: [a record was] Changed on <date/time> by <user> */I18N::translate('Changed on %1$s by %2$s', view('components/datetime', ['timestamp' => $row->record->lastChangeTimestamp()]), e($row->record->lastChangeUser())) ?>
                <?php else : ?>
                    <?= /* I18N: [a record was] Changed on <date/time> */ I18N::translate('Changed on %1$s', view('components/datetime', ['timestamp' => $row->record->lastChangeTimestamp()])) ?>
                <?php endif ?>
            </small>
        <?php endif ?>
    </a>
<?php endforeach ?>
</div>

<?php View::push('javascript') ?>
<script>
    document.getElementById("show-more-<?= e($id) ?>").addEventListener("click", function (ev) {
        document.querySelectorAll("#block-<?= e($id) ?> .d-none").forEach(function (el) {
            el.classList.remove("d-none");
        });
        ev.target.parentNode.removeChild(ev.target);
    });
</script>
<?php View::endPush() ?>
